### ISSUE TITLE
Aubess 20A - plug SW reboot each night at 3 am

### ISSUE THREAD

**Issue by ladykira2022** [kuba2k2/libretiny#137]
Hi.
I have several Aubess 20A plugs and all of them perform a SW reboot at 3 am.

They are using : v1.0.2+sha.5c4da6e on generic-bk7231n-qfn32-tuya, compiled at Jun 8 2023 09:18:46, GCC 10.3.1 (-O1)

<img width="330" alt="Screenshot 2023-06-13 at 09 03 55" src="https://github.com/kuba2k2/libretiny/assets/119303364/04367e77-8266-4eb0-b205-6cfbde0672d2">
Log:

[logs_3-aubess_logs.txt](https://github.com/kuba2k2/libretiny/files/11731191/logs_3-aubess_logs.txt)

Yaml Below:

```yaml
esphome:
  name: "3-aubess"

libretiny:
  board: generic-bk7231n-qfn32-tuya
  framework:
    version: dev

logger:

web_server:

captive_portal:

mdns:

api:
  password: !secret api_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

button:
- platform: restart
  name: Restart

debug:
  update_interval: 30s

text_sensor:
- platform: debug
  reset_reason:
    name: Reset Reason
- platform: libretiny
  version:
    name: LibreTiny Version

sensor:
- platform: uptime
  name: Uptime
- platform: hlw8012
  model: BL0937
  cf_pin:
    number: P7
    inverted: true
  cf1_pin:
    number: P6
    inverted: true
  sel_pin:
    number: P24
    inverted: true
  current:
    name: BL0937 Current
  voltage:
    name: BL0937 Voltage
  power:
    name: BL0937 Power
  energy:
    name: BL0937 Energy
  voltage_divider: 800
  current_resistor: 0.001 ohm

binary_sensor:
- platform: gpio
  id: binary_switch_1
  pin:
    number: P23
    inverted: true
    mode: INPUT_PULLUP
  on_press:
    then:
    - switch.toggle: switch_1

switch:
- platform: gpio
  id: switch_1
  name: Relay 1
  pin: P26

status_led:
  pin: P8
```
