### ISSUE TITLE
Missing components in HomeAssistant

### ISSUE THREAD

**Issue by llluis** [kuba2k2/libretiny#143]
Hi,

I can compile and upload libretiny-esphome to my Tuya device.
`INFO ESPHome 2023.6.0-dev`

Using the web_server component I can see all my other components, like buttons, switches, light, etc.
However, the device in HomeAssistant is missing some of them.

For instance, I have:
```
binary_sensor:
  - platform: gpio
    id: power_sensor
    pin:
      number: D2
      inverted: True
  - platform: gpio
    id: my_button
    pin:
      number: D4
      inverted: True
```

Those are not show in HomeAssistant. But are present in the WebServer... 

I have several other esphome/esp8266 devices working fine.

Am I missing something? Is this a known limitation?
