### ISSUE TITLE
Help with compiling for device group

### ISSUE THREAD

**Issue by ferbulous** [kuba2k2/libretiny#98]
Hi, I'm trying to get device group (dgr) working from [here](https://github.com/tony-fav/esphome-sync)
Any recommended fixes to compile it successfully in LT?

device.yml
```
esphome:
  name: aubess_wifi_mini
  name_add_mac_suffix: true
  includes:
    - ehdgr/support_device_groups_compat.h  # compatibility layer so support_device_groups_ehdgr.h need not be modified too much
    - ehdgr/support_device_groups_ehdgr.h   # support_device_groups.ino modified as minimally as possible
  on_boot:
    priority: -100
    then:
      - script.execute: dgr_start
  on_loop:
    then:
      - if:
          condition:
            switch.is_on: use_dgr
          then:
            script.execute: dgr_loop

libretuya:
  board: generic-bk7231n-qfn32-tuya
  framework:
    version: latest
  lt_config:
    LT_UART_DEFAULT_PORT: 1

external_components:
  - source: github://esphome/esphome@dev
    components: [ light ]

logger:
  hardware_uart: SERIAL1
  deassert_rts_dtr: true

api:
  password: ""
  reboot_timeout: 0s

ota:
  password: ""

web_server:
  port: 80

script:
  - id: dgr_start
    mode: single
    then:
      - lambda: |-
          EHDGR_Init("devicegrouptest");
  - id: dgr_loop
    mode: single
    then:
      - lambda: |-
          // Log EHDGR_State every 10s
          static unsigned long last_state_log_time = millis();
          if (millis() > last_state_log_time + 10000)
          {
            EHDGR_LogState();
            last_state_log_time = millis();
          }
          EHDGR_StartAndLoop();
          if (EHDGR_GetPowerState(1) != id(DGR_Relay_1).state) id(DGR_Relay_1).publish_state(EHDGR_GetPowerState(1));
  - id: dgr_end
    mode: single
    then:
      - lambda: |-
          EHDGR_Stop();

wifi:
  ssid: "wifi"
  password: "pass"

status_led:
  pin:
    number: D2
    inverted: true

output:
  - platform: gpio
    id: gpio_relay
    pin: D9

switch:
  - platform: output
    id: switch_output
    name: "Switch"
    output: gpio_relay

  - platform: restart
    name: "${friendly_name} Restart"

  - platform: template
    id: use_dgr
    name: "${friendly_name} DGR"
    optimistic: true
    on_turn_off:
      - script.execute: dgr_end

  - platform: template
    name: "${friendly_name} DGR Relay 1"
    id: DGR_Relay_1
    turn_on_action:
      - lambda: |-
          EHDGR_SetPowerState(1, 1);
    turn_off_action:
      - lambda: |-
          EHDGR_SetPowerState(1, 0);

binary_sensor:
  - platform: gpio
    id: button_tact
    pin:
      number: D4
      inverted: true
    on_click:
      then:
        - switch.toggle: switch_output
  - platform: gpio
    id: button_input
    pin:
      number: D8
      inverted: true
      mode:
        input: true
        pullup: true
    on_state:
      then:
        - switch.toggle: switch_output
```

Logs
```
Compiling .pioenvs\aubess_wifi_mini\libretuya_api\core\lt_logger.c.o
Compiling .pioenvs\aubess_wifi_mini\libretuya_api\core\main.cpp.o
Compiling .pioenvs\aubess_wifi_mini\libretuya_api\libraries\Flash\Flash.cpp.o
In file included from src/main.cpp:70:0:
src/support_device_groups_compat.h:267:60: error: 'esphome::light' has not been declared
 void EHDGR_Update5ChLightFromDGR(uint32_t device, esphome::light::LightState* light)
                                                            ^
src/support_device_groups_compat.h:267:77: error: expected ',' or '...' before '*' token
 void EHDGR_Update5ChLightFromDGR(uint32_t device, esphome::light::LightState* light)
                                                                             ^
src/support_device_groups_compat.h: In function 'void EHDGR_Update5ChLightFromDGR(uint32_t, int)':
src/support_device_groups_compat.h:270:20: error: 'light' was not declared in this scope
   bool tstate = id(light).current_values.get_state();
                    ^
src/support_device_groups_compat.h:314:29: error: 'ColorMode' has not been declared
         call.set_color_mode(ColorMode::RGB);
                             ^
src/support_device_groups_compat.h:323:29: error: 'ColorMode' has not been declared
         call.set_color_mode(ColorMode::COLD_WARM_WHITE);
                             ^
src/support_device_groups_compat.h: At global scope:
src/support_device_groups_compat.h:359:60: error: 'esphome::light' has not been declared
 void EHDGR_Update4ChLightFromDGR(uint32_t device, esphome::light::LightState* light)
                                                            ^
src/support_device_groups_compat.h:359:77: error: expected ',' or '...' before '*' token
 void EHDGR_Update4ChLightFromDGR(uint32_t device, esphome::light::LightState* light)
                                                                             ^
src/support_device_groups_compat.h: In function 'void EHDGR_Update4ChLightFromDGR(uint32_t, int)':
src/support_device_groups_compat.h:362:20: error: 'light' was not declared in this scope
   bool tstate = id(light).current_values.get_state();
                    ^
src/support_device_groups_compat.h:402:29: error: 'ColorMode' has not been declared
         call.set_color_mode(ColorMode::RGB);
                             ^
src/support_device_groups_compat.h:411:29: error: 'ColorMode' has not been declared
         call.set_color_mode(ColorMode::WHITE);
                             ^
src/support_device_groups_compat.h: At global scope:
src/support_device_groups_compat.h:447:60: error: 'esphome::light' has not been declared
 void EHDGR_Update3ChLightFromDGR(uint32_t device, esphome::light::LightState* light)
                                                            ^
src/support_device_groups_compat.h:447:77: error: expected ',' or '...' before '*' token
 void EHDGR_Update3ChLightFromDGR(uint32_t device, esphome::light::LightState* light)
                                                                             ^
src/support_device_groups_compat.h: In function 'void EHDGR_Update3ChLightFromDGR(uint32_t, int)':
src/support_device_groups_compat.h:450:20: error: 'light' was not declared in this scope
   bool tstate = id(light).current_values.get_state();
                    ^
src/support_device_groups_compat.h: At global scope:
src/support_device_groups_compat.h:533:60: error: 'esphome::light' has not been declared
 void EHDGR_Update2ChLightFromDGR(uint32_t device, esphome::light::LightState* light)
                                                            ^
src/support_device_groups_compat.h:533:77: error: expected ',' or '...' before '*' token
 void EHDGR_Update2ChLightFromDGR(uint32_t device, esphome::light::LightState* light)
                                                                             ^
src/support_device_groups_compat.h: In function 'void EHDGR_Update2ChLightFromDGR(uint32_t, int)':
src/support_device_groups_compat.h:536:20: error: 'light' was not declared in this scope
   bool tstate = id(light).current_values.get_state();
                    ^
src/support_device_groups_compat.h: At global scope:
src/support_device_groups_compat.h:604:60: error: 'esphome::light' has not been declared
 void EHDGR_Update1ChLightFromDGR(uint32_t device, esphome::light::LightState* light)
                                                            ^
src/support_device_groups_compat.h:604:77: error: expected ',' or '...' before '*' token
 void EHDGR_Update1ChLightFromDGR(uint32_t device, esphome::light::LightState* light)
                                                                             ^
src/support_device_groups_compat.h: In function 'void EHDGR_Update1ChLightFromDGR(uint32_t, int)':
src/support_device_groups_compat.h:607:20: error: 'light' was not declared in this scope
   bool tstate = id(light).current_values.get_state();
                    ^
src/support_device_groups_compat.h: At global scope:
src/support_device_groups_compat.h:655:60: error: 'esphome::light' has not been declared
 void EHDGR_Update0ChLightFromDGR(uint32_t device, esphome::light::LightState* light)
                                                            ^
src/support_device_groups_compat.h:655:77: error: expected ',' or '...' before '*' token
 void EHDGR_Update0ChLightFromDGR(uint32_t device, esphome::light::LightState* light)
                                                                             ^
src/support_device_groups_compat.h: In function 'void EHDGR_Update0ChLightFromDGR(uint32_t, int)':
src/support_device_groups_compat.h:658:20: error: 'light' was not declared in this scope
   bool tstate = id(light).current_values.get_state();
                    ^
In file included from src/main.cpp:71:0:
src/support_device_groups_ehdgr.h: At global scope:
src/support_device_groups_ehdgr.h:65:1: error: 'WiFiUDP' does not name a type
 WiFiUDP device_groups_udp;
 ^
In file included from src/main.cpp:71:0:
src/support_device_groups_ehdgr.h: In function 'void DeviceGroupsStart()':
src/support_device_groups_ehdgr.h:188:10: error: 'device_groups_udp' was not declared in this scope
     if (!device_groups_udp.beginMulticast(WiFi.localIP(), IPAddress(DEVICE_GROUPS_ADDRESS), DEVICE_GROUPS_PORT)) {
          ^
src/support_device_groups_ehdgr.h:197:30: error: call of overloaded 'millis()' is ambiguous
     next_check_time = millis() + 2000;
                              ^
src/support_device_groups_ehdgr.h:197:30: note: candidates are:
In file included from C:/Users/theba/.platformio/packages/framework-arduino-api/api/Interrupts.h:8:0,
                 from C:/Users/theba/.platformio/packages/framework-arduino-api/api/ArduinoAPI.h:29,
                 from C:/Users/theba/.platformio/platforms/libretuya/arduino/beken-72xx/cores/arduino/Arduino.h:10,
                 from <command-line>:0:
C:/Users/theba/.platformio/packages/framework-arduino-api/api/Common.h:103:15: note: long unsigned int millis()
 unsigned long millis(void);
               ^
In file included from src/esphome/core/application.h:7:0,
                 from src/esphome\components\api\api_connection.h:7,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/hal.h:37:10: note: uint32_t esphome::millis()
 uint32_t millis();
          ^
In file included from src/main.cpp:71:0:
src/support_device_groups_ehdgr.h: In function 'void DeviceGroupsStop()':
src/support_device_groups_ehdgr.h:211:3: error: 'device_groups_udp' was not declared in this scope
   device_groups_udp.flush();
   ^
Compiling .pioenvs\aubess_wifi_mini\libretuya_api\libraries\HTTPClient\HTTPClient.cpp.o
In file included from src/main.cpp:71:0:
src/support_device_groups_ehdgr.h: In function 'void SendReceiveDeviceGroupMessage(device_group*, device_group_member*, uint8_t*, int, bool)':
src/support_device_groups_ehdgr.h:499:11: error: 'device_groups_udp' was not declared in this scope
       if (device_groups_udp.beginPacket(ip_address, DEVICE_GROUPS_PORT)) {
           ^
src/support_device_groups_ehdgr.h:503:15: error: call of overloaded 'delay(int)' is ambiguous
       delay(10);
               ^
src/support_device_groups_ehdgr.h:503:15: note: candidates are:
In file included from C:/Users/theba/.platformio/platforms/libretuya/arduino/beken-72xx/cores/arduino/Arduino.h:15:0,
                 from <command-line>:0:
C:/Users/theba/.platformio/platforms/libretuya/arduino/beken-72xx/cores/arduino/WVariant.h:13:51: note: void delay(long unsigned int)
 static inline __attribute__((always_inline)) void delay(unsigned long ms) {
                                                   ^
In file included from src/esphome/core/application.h:7:0,
                 from src/esphome\components\api\api_connection.h:7,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/hal.h:39:6: note: void esphome::delay(uint32_t)
 void delay(uint32_t ms);
      ^
In file included from src/main.cpp:71:0:
src/support_device_groups_ehdgr.h: In function 'bool _SendDeviceGroupMessage(int32_t, DevGroupMessageType, ...)':
src/support_device_groups_ehdgr.h:872:25: error: call of overloaded 'millis()' is ambiguous
   uint32_t now = millis();
                         ^
src/support_device_groups_ehdgr.h:872:25: note: candidates are:
In file included from C:/Users/theba/.platformio/packages/framework-arduino-api/api/Interrupts.h:8:0,
                 from C:/Users/theba/.platformio/packages/framework-arduino-api/api/ArduinoAPI.h:29,
                 from C:/Users/theba/.platformio/platforms/libretuya/arduino/beken-72xx/cores/arduino/Arduino.h:10,
                 from <command-line>:0:
C:/Users/theba/.platformio/packages/framework-arduino-api/api/Common.h:103:15: note: long unsigned int millis()
 unsigned long millis(void);
               ^
In file included from src/esphome/core/application.h:7:0,
                 from src/esphome\components\api\api_connection.h:7,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/hal.h:37:10: note: uint32_t esphome::millis()
 uint32_t millis();
          ^
In file included from src/main.cpp:71:0:
src/support_device_groups_ehdgr.h: In function 'void ProcessDeviceGroupMessage(uint8_t*, int)':
src/support_device_groups_ehdgr.h:903:25: error: 'device_groups_udp' was not declared in this scope
   IPAddress remote_ip = device_groups_udp.remoteIP();
                         ^
src/support_device_groups_ehdgr.h:915:50: error: call of overloaded 'millis()' is ambiguous
       device_group->member_timeout_time = millis() + DGR_MEMBER_TIMEOUT;
                                                  ^
src/support_device_groups_ehdgr.h:915:50: note: candidates are:
In file included from C:/Users/theba/.platformio/packages/framework-arduino-api/api/Interrupts.h:8:0,
                 from C:/Users/theba/.platformio/packages/framework-arduino-api/api/ArduinoAPI.h:29,
                 from C:/Users/theba/.platformio/platforms/libretuya/arduino/beken-72xx/cores/arduino/Arduino.h:10,
                 from <command-line>:0:
C:/Users/theba/.platformio/packages/framework-arduino-api/api/Common.h:103:15: note: long unsigned int millis()
 unsigned long millis(void);
               ^
In file included from src/esphome/core/application.h:7:0,
                 from src/esphome\components\api\api_connection.h:7,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/hal.h:37:10: note: uint32_t esphome::millis()
 uint32_t millis();
          ^
In file included from src/main.cpp:71:0:
src/support_device_groups_ehdgr.h: In function 'void DeviceGroupsLoop()':
src/support_device_groups_ehdgr.h:948:10: error: 'device_groups_udp' was not declared in this scope
   while (device_groups_udp.parsePacket()) {
          ^
src/support_device_groups_ehdgr.h:959:25: error: call of overloaded 'millis()' is ambiguous
   uint32_t now = millis();
                         ^
src/support_device_groups_ehdgr.h:959:25: note: candidates are:
In file included from C:/Users/theba/.platformio/packages/framework-arduino-api/api/Interrupts.h:8:0,
                 from C:/Users/theba/.platformio/packages/framework-arduino-api/api/ArduinoAPI.h:29,
                 from C:/Users/theba/.platformio/platforms/libretuya/arduino/beken-72xx/cores/arduino/Arduino.h:10,
                 from <command-line>:0:
C:/Users/theba/.platformio/packages/framework-arduino-api/api/Common.h:103:15: note: long unsigned int millis()
 unsigned long millis(void);
               ^
In file included from src/esphome/core/application.h:7:0,
                 from src/esphome\components\api\api_connection.h:7,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/hal.h:37:10: note: uint32_t esphome::millis()
 uint32_t millis();
          ^
aubess_wifi_mini.yml: In lambda function:
aubess_wifi_mini.yml:55:57: error: call of overloaded 'millis()' is ambiguous
aubess_wifi_mini.yml:55:57: note: candidates are:
In file included from C:/Users/theba/.platformio/packages/framework-arduino-api/api/Interrupts.h:8:0,
                 from C:/Users/theba/.platformio/packages/framework-arduino-api/api/ArduinoAPI.h:29,
                 from C:/Users/theba/.platformio/platforms/libretuya/arduino/beken-72xx/cores/arduino/Arduino.h:10,
                 from <command-line>:0:
C:/Users/theba/.platformio/packages/framework-arduino-api/api/Common.h:103:15: note: long unsigned int millis()
 unsigned long millis(void);
               ^
In file included from src/esphome/core/application.h:7:0,
                 from src/esphome\components\api\api_connection.h:7,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/hal.h:37:10: note: uint32_t esphome::millis()
 uint32_t millis();
          ^
aubess_wifi_mini.yml:56:18: error: call of overloaded 'millis()' is ambiguous
aubess_wifi_mini.yml:56:18: note: candidates are:
In file included from C:/Users/theba/.platformio/packages/framework-arduino-api/api/Interrupts.h:8:0,
                 from C:/Users/theba/.platformio/packages/framework-arduino-api/api/ArduinoAPI.h:29,
                 from C:/Users/theba/.platformio/platforms/libretuya/arduino/beken-72xx/cores/arduino/Arduino.h:10,
                 from <command-line>:0:
C:/Users/theba/.platformio/packages/framework-arduino-api/api/Common.h:103:15: note: long unsigned int millis()
 unsigned long millis(void);
               ^
In file included from src/esphome/core/application.h:7:0,
                 from src/esphome\components\api\api_connection.h:7,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/hal.h:37:10: note: uint32_t esphome::millis()
 uint32_t millis();
          ^
aubess_wifi_mini.yml:59:38: error: call of overloaded 'millis()' is ambiguous
aubess_wifi_mini.yml:59:38: note: candidates are:
In file included from C:/Users/theba/.platformio/packages/framework-arduino-api/api/Interrupts.h:8:0,
                 from C:/Users/theba/.platformio/packages/framework-arduino-api/api/ArduinoAPI.h:29,
                 from C:/Users/theba/.platformio/platforms/libretuya/arduino/beken-72xx/cores/arduino/Arduino.h:10,
                 from <command-line>:0:
C:/Users/theba/.platformio/packages/framework-arduino-api/api/Common.h:103:15: note: long unsigned int millis()
 unsigned long millis(void);
               ^
In file included from src/esphome/core/application.h:7:0,
                 from src/esphome\components\api\api_connection.h:7,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/hal.h:37:10: note: uint32_t esphome::millis()
 uint32_t millis();
          ^
```
